### ISSUE TITLE
Improve trait filtering

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#183]
When a collection has a lot of traits, the scroll is extremely long. Maybe we should "paginate" the list of traits or display only the main ones, then the rest are accessible by search.

https://user-images.githubusercontent.com/1783126/218673745-8820d311-61d3-4179-88d2-6897ba5f317d.mov

**Comment by ismailToyran** [comment]
This one was slowing page by a lot. In order to fix that, after this issue has been created, we've decreased the number of traits we could show on this page to 50 w Nicolas.

If we want to add pagination and rework this component and how it functions, there needs to be new flow.
- New searchbar dedicated to traits
- New pagination for traits
- Improving traits query for filter integration (currently we don't have any filtering on traits, just getting first 50)

What do you think? Should I ask Emmanuel?

**Comment by antho1404** [comment]
I am good to close this one for now as we already have a limit and the rest is searchable, I don't think pagination will be interesting as it will most likely make the UX terrible
