### ISSUE TITLE
Place bid button doesn't trigger any action after page refresh

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#343]
After reloading the website on the page to create a bid, the "place a bid" button doesn't trigger any action.
https://dev.uaan.liteflow.com/tokens/80001-0x7c68c3c59ceb245733a2fdeb47f5f7d6dbcc65b3-42728329798185476104569684045014434977602555793693139688081182813192562446854/bid

This only occurs when I go to the page, then refresh the page, then fill the form and try to create the bid. No issue when navigating to the page and not refreshing it.

I remember reporting similar issue. Let's make sure the fix is implemented on every page with a form.

**Comment by antho1404** [comment]
Could you record a video or something like that? In my case, the button "place a bid" is disabled because I don't have a balance on this chain/currency (most likely due to the issue with polygon testnet network down).

Tested on other chains/currencies, and I don't have any issues on local, dev, demo, or I am not testing correctly.

**Comment by NicolasMahe** [comment]
Indeed it has been fixed by PR https://github.com/liteflow-labs/starter-kit/pull/330. Good job @ismailToyran 👍 

Here is the Vercel's deployment when this issue was still occurring: https://vercel.com/liteflow/nft-test-uaan/2RhyyimM9Hd6nCnaDnK7fq55y7QB
