### ISSUE TITLE
Activity panel, fixed price query issue

### ISSUE THREAD

**Issue by ismailToyran** [liteflow-labs/starter-kit#73]
I've talked with Manu and it seems we've this issue on this repository as well.
He also told me about this issue but it seems it wasn't being tracked on anywhere (which he thinks is critical issue)
So right on the below image, even though I've changed ownership of the asset, it still shows on sales page but with no button (as button checks ownership of the item already)
So I believe this issue happening because we're not checking ownership while filtering on this page.
What it actually must show is on the 2nd picture.

![image](https://user-images.githubusercontent.com/33982052/193553756-ea0b175b-35cc-40bf-bbc4-f19ced229e2e.png)
![image](https://user-images.githubusercontent.com/33982052/193554596-0826f119-7d84-471c-af38-850138f669f8.png)

When this issue gets fixed by it's linked PR, please make sure to apply on all other platforms as I will be working on O-mee.

**Comment by EmmanuelDrouin** [comment]
@ismailToyran this issue was indeed on the fact that once transferred the previous owner doesn't have any button display anymore in the row to cancel his listing when he should be able to do so (no matter if he has the ownership of the NFT or not) but we NEED to keep displaying the listing so the user is aware of it and can decide to cancel it or let it expire.

Regarding the fact that we fixed this on O-MEE, @ismailToyran is it also fixed on the Starter kit or the fix was only applied to O-MEE?

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this is not related to the starter kit
